import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Velix Terms of Service — rules and guidelines for using the Velix AI code generation platform.",
  robots: { index: true, follow: true },
};

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-background text-foreground">
            <div className="max-w-3xl mx-auto px-6 py-12">
                <Link href="/" className="inline-flex items-center gap-2 text-xs text-muted hover:text-foreground transition-colors mb-8">
                    <ArrowLeft className="w-3 h-3" /> Back to Home
                </Link>

                <h1 className="text-2xl font-bold mb-2">Terms of Service</h1>
                <p className="text-xs text-muted mb-8">Last updated: June 21, 2026</p>

                <div className="space-y-6 text-sm leading-relaxed text-foreground/80">
                    <section>
                        <h2 className="text-base font-semibold mb-2 text-foreground">1. Acceptance of Terms</h2>
                        <p>By accessing or using Velix AI (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service. We reserve the right to modify these terms at any time without prior notice. Continued use constitutes acceptance of any changes.</p>
                    </section>

                    <section>
                        <h2 className="text-base font-semibold mb-2 text-foreground">2. As-Is Disclaimer</h2>
                        <p><strong>THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED.</strong> We make no warranties, expressed or implied, regarding the Service&apos;s reliability, accuracy, availability, fitness for a particular purpose, or non-infringement. You use the Service at your own risk. We are not responsible for any damage, data loss, or consequences arising from use of the Service or reliance on any output generated by the Service.</p>
                    </section>

                    <section>
                        <h2 className="text-base font-semibold mb-2 text-foreground">3. AI-Generated Content</h2>
                        <p>All code, text, and other content generated by the Service&apos;s AI is provided as-is. We do not guarantee its correctness, completeness,安全性, or suitability for any purpose. You are solely responsible for reviewing, testing, and validating any AI-generated output before use. We are not liable for any consequences resulting from use of AI-generated content.</p>
                    </section>

                    <section>
                        <h2 className="text-base font-semibold mb-2 text-foreground">4. User Accounts</h2>
                        <p>You are responsible for maintaining the confidentiality of your account credentials. We are not liable for any unauthorized access to your account. You agree to notify us immediately of any unauthorized use. We reserve the right to suspend or terminate accounts at our sole discretion without prior notice or liability.</p>
                    </section>

                    <section>
                        <h2 className="text-base font-semibold mb-2 text-foreground">5. Credits and Payments</h2>
                        <p>Credits are non-refundable and have no monetary value. We reserve the right to modify credit pricing, availability, and redemption terms at any time without notice. Purchased credits are non-transferable. We are not responsible for any unauthorized credit deductions resulting from your account security lapses.</p>
                    </section>

                    <section>
                        <h2 className="text-base font-semibold mb-2 text-foreground">6. Intellectual Property</h2>
                        <p>You retain ownership of code you write. AI-generated code is provided to you under the same terms. We claim no ownership over your projects. However, we are not responsible for any intellectual property infringement that may arise from AI-generated content. You are solely responsible for ensuring your use complies with applicable laws and third-party rights.</p>
                    </section>

                    <section>
                        <h2 className="text-base font-semibold mb-2 text-foreground">7. Third-Party Integrations</h2>
                        <p>The Service integrates with third-party APIs (including but not limited to NVIDIA, OpenRouter, Supabase, and Discord). We are <strong>NOT</strong> affiliated with, endorsed by, or connected to OpenRouter, NVIDIA, Mojang Studios, Microsoft, Supabase, Discord Inc., or any other organization or company whose services may be used with this software.</p>
                        <p className="mt-2">Your use of third-party services is subject to their respective terms. It is <strong>your responsibility</strong> to review and comply with the terms of service of any third-party API provider. Some providers (including NVIDIA) may <strong>not permit</strong> the use of free trial or free tier API keys for commercial applications. Using such services in violation of their terms is solely your responsibility.</p>
                        <p className="mt-2">We disclaim all liability arising from third-party service interruptions, failures, or violations of third-party terms of service.</p>
                    </section>

                    <section>
                        <h2 className="text-base font-semibold mb-2 text-foreground">8. Limitation of Liability</h2>
                        <p><strong>IN NO EVENT SHALL WE BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF DATA, REVENUE, PROFITS, OR BUSINESS OPPORTUNITIES, ARISING FROM USE OF THE SERVICE, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</strong></p>
                    </section>

                    <section>
                        <h2 className="text-base font-semibold mb-2 text-foreground">9. Indemnification</h2>
                        <p>You agree to indemnify, defend, and hold harmless Velix AI, its operators, contributors, and affiliates from any claims, losses, damages, liabilities, costs, and expenses arising from your use of the Service or violation of these Terms.</p>
                    </section>

                    <section>
                        <h2 className="text-base font-semibold mb-2 text-foreground">10. Service Availability</h2>
                        <p>We do not guarantee uninterrupted or error-free operation. We may suspend, modify, or discontinue the Service at any time without notice or liability. We are not responsible for any data loss resulting from service interruptions.</p>
                    </section>

                    <section>
                        <h2 className="text-base font-semibold mb-2 text-foreground">11. Governing Law</h2>
                        <p>These Terms are governed by applicable laws without regard to conflict of law principles. Any disputes shall be resolved in the applicable jurisdiction.</p>
                    </section>

                    <section>
                        <h2 className="text-base font-semibold mb-2 text-foreground">12. Contact</h2>
                        <p>For questions about these Terms, join our Discord: <a href="https://discord.gg/FD6QrzeATb" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">discord.gg/FD6QrzeATb</a></p>
                    </section>
                </div>
            </div>
        </div>
    );
}
